name: analysis
channels:
  - defaults
dependencies:
  - python<3.12
  - pip
  - matplotlib
  - tqdm
  - scikit-learn
  - scipy
  - numpy
  - pandas
  - tensorly::tensorly
  - pip:
    - -r ../IEEG_Pipelines/envs/requirements.txt