name: analysis
channels:
  - conda
dependencies:
  - python
  - pip
  - matplotlib
  - tqdm
  - numpy<2.0
  - pillow
  - pytorch-nightly::pytorch
  - pytorch-nightly::cpuonly
  - lightning
  - conda-forge::nimfa
  - pip:
    - ..\..\IEEG_Pipelines\.

