name: analysis
channels:
  - defaults
  - conda-forge
  - tensorly
dependencies:
  - python<3.11
  - pip
  - matplotlib
  - tqdm
  - scikit-learn
  - tslearn
  - scipy
  - numpy
  - pandas
  - Cython
  - nose
  - tensorly
  - pip:
    - -r requirements.txt