name: analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python<3.10
  - pip
  - matplotlib
  - tqdm
  - scikit-learn
  - tslearn
  - scipy
  - numpy
  - pandas
  - h5py
  - pip:
    - -r requirements.txt