name: analysis
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - matplotlib
  - tqdm
  - numpy<2.0
  - nimfa
  - pip:
    - git+https://github.com/coganlab/IEEG_Pipelines.git@mri_explicit
