name: analysis
dependencies:
  - python
  - pip
  - matplotlib
  - tqdm
  - numpy<2.0
  - notebook
  - pillow
  - pip:
    - git+https://github.com/coganlab/IEEG_Pipelines.git@mri_explicit
    - nimfa
