name: analysis
channels:
  - defaults
  - pytorch-nightly
  - nvidia
dependencies:
  - python
  - pip
  - matplotlib
  - tqdm
  - numpy
  - pillow
  - pytorch
  - pytorch-cuda
  - conda-forge::lightning
  - conda-forge::nimfa
  - pip:
    - -e ../../IEEG_Pipelines
    - -e ../../slicetca

