name: analysis
channels:
  - pytorch-nightly
  - nvidia
dependencies:
  - python
  - pip
  - numpy
  - torchvision
  - torchaudio
  - pytorch
  - pytorch-cuda
  - conda-forge::lightning
  - conda-forge::nimfa
  - pip:
    - -e ../../IEEG_Pipelines
    - -e ../../slicetca
