name: ieeg
channels:
  - defaults
dependencies:
  - python<3.12
  - pip
  - matplotlib
  - tqdm
  - scikit-learn
  - scipy
  - numpy
  - pandas
  - numba
  - conda-forge::nimfa
  - pip:
    - -r ../IEEG_Pipelines/envs/requirements.txt